GET http://localhost:3030/api/users


###
GET http://localhost:3030/api/users/4dd85bb2-2eab-4b1d-b243-0d3af692c831


###

GET http://localhost:3030/api/users/correo
Content-Type: application/json

{
    "correo": "ivandavidgomezsilva@hotmail.com",
    "contraseña": "Idgs2603"
}


###
POST http://localhost:3030/api/users
Content-Type: application/json

{
    "nombre": "Monica Silva",
    "correo": "monitatinet@yacmail.com",
    "contraseña": "Idgs2603"
}

###

PATCH http://localhost:3030/api/users/0a369bd9-e2c8-406f-9aed-18dec6d4efbf
Content-Type: application/json

{
    "direccionEnvio": {
        "calle": "14",
        "ciudad": "Bucaramanga",
        "pais": "Colombia",
        "codigoPostal": "680004"
    }
    
}

###

DELETE http://localhost:3030/api/users/6bcb7b9b-b22c-4a66-a4a3-c90beb84ec25