GET http://localhost:3030/api/users


###
GET http://localhost:3030/api/users/bda285c8-e1fe-4b88-a310-e8c48ebc73d9/photoAndName


###

GET http://localhost:3030/api/users/correo
Content-Type: application/json

{
    "correo": "ivandavidgomezsilva@hotmail.com",
    "contraseña": "Idgs2603"
}


###
POST http://localhost:3030/api/users
Content-Type: application/json

{
    "nombre": "Monica Silva",
    "correo": "monitatinet@cmail.com",
    "contraseña": "Idgs2603"
}

###

PATCH http://localhost:3030/api/users/0a369bd9-e2c8-406f-9aed-18dec6d4efbf
Content-Type: application/json

{
    "direccionEnvio": {
        "calle": "14",
        "ciudad": "Bucaramanga",
        "pais": "Colombia",
        "codigoPostal": "680004"
    }
    
}

###

PATCH http://localhost:3030/api/users/857857d1-afdd-411d-b41a-be427d1ff186
Content-Type: application/json

{
    "favoritos": "ac6773d2-9166-4840-b5cd-995a49b19031",
    "accion": "eliminar"
    
}

###

DELETE http://localhost:3030/api/users/6bcb7b9b-b22c-4a66-a4a3-c90beb84ec25