# Get all books
GET http://localhost:3030/api/books

### Get all review books
GET http://localhost:3030/api/books/review

### 
POST http://localhost:3030/api/books

Content-Type: application/json
{
  "titulo": "Sample Book",
  "autor": "Sample Author",
  "precio": 100,
  "images": ["sample-image.png"]
}

### Create a new review book
POST http://localhost:3030/api/books/review
Content-Type: application/json

{
  "titulo": "Sample Review Book",
  "autor": "Sample Author",
  "precio": 100,
  "images": ["sample-image.png"]
}

### Predict book info
POST http://localhost:3030/api/books/predictInfo
Content-Type: multipart/form-data

### Generate book description
POST http://localhost:3030/api/books/generateDescription

Content-Type: application/json
{
  "titulo": "Sample Title",
  "autor": "Sample Author"
}

### Get books by collection
POST http://localhost:3030/api/books/getBooksByCollection
Content-Type: application/json

{
  "collectionId": "sample-collection-id"
}

### For You Page
GET http://localhost:3030/api/books/fyp

### Get book by query
GET http://localhost:3030/api/books/query?q=sample-query

### Get books by query with filters
GET http://localhost:3030/api/books/query/filters?q=sample-query&filter=sample-filter

### Search book by title
GET http://localhost:3030/api/books/search/sample-title

### Get favorites by user
GET http://localhost:3030/api/books/getFavoritesByUser/sample-user-id

### Get book by ID
GET http://localhost:3030/api/books/sample-book-id

### Update review book
PUT http://localhost:3030/api/books/review/sample-book-id
Content-Type: application/json

{
  "titulo": "Updated Review Book",
  "estado": "Updated"
}

# Update book
PUT http://localhost:3030/api/books/sample-book-id
Content-Type: application/json

{
  "titulo": "Updated Book",
  "estado": "Updated"
}

# Delete review book
DELETE http://localhost:3030/api/books/review/sample-book-id

# Delete book
DELETE http://localhost:3030/api/books/sample-book-id
###

GET http://localhost:3030/uploads/1729454065315-576691826.png