GET http://localhost:3030/api/collections


###
GET http://localhost:3030/api/collections/id/5b14f0b8-1501-4a34-b90d-c87d0eea6a9b



###
POST http://localhost:3030/api/collections
Content-Type: application/json

{
    "nombre": "Dicen que estamos locos"
}

###

POST http://localhost:3030/api/collections/addToCollection?collectionId=bfed12f2-8814-438a-a22e-43d4a6d33d96&bookId=3cd4d6ad-df7c-4e0f-beb9-394de48ce33d

###

DELETE http://localhost:3030/api/collections/5b14f0b8-1501-4a34-b90d-c87d0eea6a9b


#Conversation
###
PATCH http://localhost:3030/api/collections/0e17735a-8b8b-40ba-b4f5-62c89ab7d29c
Content-Type: application/json

{
    "nombre": "ñaña"
}
###
GET http://localhost:3030/api/conversations/afd647d7-3b09-495e-9f6e-0421c16b28d6



###
POST http://localhost:3030/api/conversations
Content-Type: application/json

{
    "users": ["857857d1-afdd-411d-b41a-be427d1ff186","1816d212-7dc5-4d74-bb9d-e0d97bf60d27"]
}

###


DELETE http://localhost:3030/api/conversations/4e22d65d-48b7-485f-a017-c3d296ddefae