GET http://localhost:3030/api/users


###
GET http://localhost:3030/api/users/bda285c8-e1fe-4b88-a310-e8c48ebc73d9/photoAndName


###

GET http://localhost:3030/api/users/login
Content-Type: application/json

{
    "correo": "ivandavidgomezsilva@hotmail.com",
    "contraseña": "Idgs2603"
}


###
POST http://localhost:3030/api/users
Content-Type: application/json

{
    "nombre": "Yanae",
    "correo": "ivandavidgomezsilva@sanpedro.edu.co",
    "contraseña": "Idgs2603"
}

###

PATCH http://localhost:3030/api/users/0a369bd9-e2c8-406f-9aed-18dec6d4efbf
Content-Type: application/json

{
    "direccionEnvio": {
        "calle": "14",
        "ciudad": "Bucaramanga",
        "pais": "Colombia",
        "codigoPostal": "680004"
    }
    
}

###

PATCH http://localhost:3030/api/users/857857d1-afdd-411d-b41a-be427d1ff186
Content-Type: application/json

{
    "favoritos": "ac6773d2-9166-4840-b5cd-995a49b19031",
    "accion": "eliminar"
    
}

###

DELETE http://localhost:3030/api/users/6bcb7b9b-b22c-4a66-a4a3-c90beb84ec25

###
POST http://localhost:3030/api/users/sendValidationEmail
Content-Type: application/json

{
    "correo": "ivandavidgomezsilva@hotmail.com",
    "nombre": "Ivan David Gomez Silva",
    "_id": "857857d1-afdd-411d-b41a-be427d1ff186"
}

###
GET http://localhost:3030/api/users/validateUser/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI4MzZlMTUxYi00M2FlLTQ4YTAtODM1Mi0xN2FkMzA5ZDgwNjgiLCJjb3JyZW8iOiJpdmFuZGF2aWRnb21lenNpbHZhQGdtYWlsLmNvbSIsImlhdCI6MTczMzM1Nzg1NSwiZXhwIjoxNzMzMzYxNDU1fQ.SgKAGJsvlLoJfo7ViTbk3hRIwYuYQV6NMzdkq6zJIqc

###
GET http://localhost:3030/api/users/validateUser/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI4MzZlMTUxYi00M2FlLTQ4YTAtODM1Mi0xN2FkMzA5ZDgwNjgiLCJjb3JyZW8iOiJpdmFuZGF2aWRnb21lenNpbHZhQGdtYWlsLmNvbSIsImlhdCI6MTczMzM1Nzg1NSwiZXhwIjoxNzMzMzYxNDU1fQ.SgKAGJsvlLoJfo7ViTbk3hRIwYuYQV6NMzdkq6zJIqc
###
GET http://localhost:3030/api/users/balance/1816d212-7dc5-4d74-bb9d-e0d97bf60d27

###

POST http://localhost:3030/api/users/newCollection
Content-Type: application/json

{
    "collectionName": "Aña",
    "userId": "857857d1-afdd-411d-b41a-be427d1ff186"
}

###

POST http://localhost:3030/api/users/addToCollection
Content-Type: application/json

{
    "collectionName": "Aña",
    "bookId": "836e151b-43ae-48a0-8352-17ad309d8068",
    "userId": "857857d1-afdd-411d-b41a-be427d1ff186"
}

###

POST http://localhost:3030/api/users/getBooksByCollection
Content-Type: application/json

{
    "collection": {
        "nombre": "Aña",
        "librosIds": [
          "221f695c-69a3-4dee-98e1-0ab4565a734c",
          "836e151b-43ae-48a0-8352-17ad309d8068",
          "e93345c4-ca50-4919-ba85-4dcf00882673"
        ]
    }
}