const generos = [
    "Novela",
    "Ciencia ficción",
    "Fantasía",
    "Misterio",
    "Biografía",
    "Romance",
    "Terror",
    "Histórica",
    "Poesía",
    "No ficción",
    "Literatura juvenil",
    "Thriller",
    "Policiaca",
    "Aventura",
    "Drama",
    "Autoayuda",
    "Ensayo",
    "Educativo",
    "Literatura contemporánea",
    "Literatura clásica",
    "Ficción histórica",
    "Cuento",
    "Ciencia popular",
    "Literatura erótica",
    "Ficción especulativa",
    "Gótico",
    "Steampunk",
    "Magical realism",
    "Parodia",
    "Dystopía",
    "Realismo mágico",
    "Crónica",
    "Sátira",
    "Ficción psicológica",
    "Ficción literaria",
    "Relato corto",
    "Ficción de aventuras",
    "Amor",
    "Ficción familiar",
    "Filosofía",
    "Salud",
    "Gastronomía",
    "Cocina",
    "Ciencias políticas",
    "Tecnología",
    "Narrativa gráfica",
    "Graphic novel",
    "Ciencia ficción distópica",
    "Ficción alternativa",
    "Antología",
    "Novela gráfica",
    "Narrativa no lineal"
  ];
  const idiomas = [
    "Español",
    "Inglés",
    "Francés",
    "Alemán",
    "Italiano",
    "Portugués",
    "Ruso",
    "Chino (Mandarín)",
    "Japonés",
    "Coreano",
    "Árabe",
    "Hindi",
    "Bengalí",
    "Turco",
    "Vietnamita",
    "Polaco",
    "Holandés",
    "Sueco",
    "Danés",
    "Noruego",
    "Finlandés",
    "Checo",
    "Húngaro",
    "Rumano",
    "Griego",
    "Hebreo",
    "Tailandés",
    "Ucraniano",
    "Malay",
    "Filipino (Tagalo)",
    "Indonesio",
    "Swahili",
    "Persa (Farsi)",
    "Serbio",
    "Croata",
    "Búlgaro",
    "Eslovaco",
    "Esloveno",
    "Catalán",
    "Gallego",
    "Vasco",
    "Latín",
    "Aragonés",
    "Sánscrito",
    "Tamil",
    "Telugu",
    "Gujarati",
    "Punjabi"
  ];
  
  export { generos, idiomas }